### PR TITLE
Numpy 2.0 support

### PR DESCRIPTION
**Pull request by dkriegner**
Enforce building with numpy-2.0 to get universal wheels.

### CODE REVIEW

**Comment by dkriegner** [comment]
I could imagine that the changes of pyproject.toml annoy packagers. @picca: do you have any comment or suggestion for this? Or will you just patch it out on Debian anyways?

I am still gonna test this with Gentoo ebuilds and report back here.

**Comment by picca** [comment]
> I could imagine that the changes of pyproject.toml annoy packagers. @picca: do
> you have any comment or suggestion for this? Or will you just patch it out on
> Debian anyways?

It you package is compatible with numpy 2.x and numpy1.x, what is the right way to express this constrain in pyproject ?

Debian is not yet ready to upload numpy 2.x, there is plenty of packages to upload with numpy 2 fixes.
This will take a long time...

**Comment by dkriegner** [comment]
The package works seems to work with both numpy 1.x and numpy 2.x. But to get wheel files for PyPI these wheels have to be built using numpy 2.x since they otherwise won't work with both numpy versions. What I use in pyproject.toml is what is explicitly recommended by [numpy](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling). 

I believe Debian can likely remove this numpy-2.0 dependency for the build system.
If I would know a way to introduce this build requirement only for the cibuildwheel pipeline on Azure this might be a better option but the way it's now protects the users from breaking their xrayutilities installation if they update numpy.

**Comment by picca** [comment]
ok, we can patch pyproject in Debian.

Cheers

Fred

**Comment by dkriegner** [comment]
With Gentoo ebuilds this seems to still work just fine since they seem to ignore the dependencies in pyproject.toml in favor of looking the ones defined in the ebuild. merging

**Pull request merged**
